name: Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            composer install
            php artisan optimize:clear
            php artisan migrate --force
            php artisan db:seed TestServerSeeder
            npm install
            npm run prod
